version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: karolis
      POSTGRES_PASSWORD: karolis
      POSTGRES_DB: project-management-app